### ISSUE TITLE
The algorithm to compute the derived property should use EAW more

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#16]
This is a feedback from Asmus.

In the section 4 Data File of the [L2/24-057], it helps if it uses EAW as one of primary properties to derive from when defining values for new code points.

[L2/24-057]: https://www.unicode.org/L2/L2024/24057-auto-spacing-prop.pdf

**Comment by asmusf** [comment]
One thing that I would have expected is that code points that have EAW value of "A" would need to have context dependent resolution of for EA spacing as well. But looking at the document I don't see that.

Is there a tacit assumption that these behave as if being resolved one way or another?

The set of characters with value EAW=A should have an intersection with the set of characters that were unified between narrow and wide character sets. And some of these unifications are now giving rise to  variation selectors.

I guess I still need to understand better how the new property relates to EAW.

For example, there are two pairs of characters and only two pairs where a character with spacing value W has EAW=N. (They are tone marks).  I would like to understand whether Unicode's EAW classification for them is incorrect or whether they should have been classified as A.

Also, there is no case of  W assigned to a character with EAW=A. Which means that the algorithm treats all EAW=A characters as resolved to "Narrow" (or they aren't letters). I would like to understand better whether that assumption holds without exception.

**Comment by kojiishi** [comment]
> One thing that I would have expected is that code points that have EAW value of "A" would need to have context dependent resolution of for EA spacing as well. But looking at the document I don't see that.

You're right, `EA=A` is hard. As you pointed out, to determine whether `EA=A` is wide or narrow, using context is one most reasonable way, but it's still heuristic. If we want the algorithm to insert spacing between all half and full width characters, the algorithm will need more deterministic way to do it, such as what @macnmm is talking about in #17.

The approach JLREQ and CLREQ took here is to rely on heuristics instead, so this doesn't produce always the result authors might have expected. But also as you pointed out in a separate thread, the goal of this spec is about "a stable default rule of inserting the spacing for the purpose of reliable document interchange", and the spec also states that "The actual choice for the property values should result in a reasonable or legible default, but it may not be publishing-material quality, and it may not be a good choice if used in a specific style or context", the error ratio of the heuristic is likely not too different from using context.

There was exactly the same discussion in UAX#50, as every single existing system sets full width characters upright and half width characters rotated, but UAX#50 assigned one way or another by heuristic, logical similarity, or some other methods. So UAX#50 does produce different results from the existing systems, but I hope you agree that it can still serve the purpose of "reliable document interchange".

> Is there a tacit assumption that these behave as if being resolved one way or another?

So yes, similar to UAX#50, this spec defines one way or another, knowing that there will be cases where it behaves differently from what authors expect. With the [data file in a spreadsheet](https://docs.google.com/spreadsheets/d/1Y8gIy5ExavkUD3SWz8cgXvns8xfawfZh6-kaLT7Dju8/edit#gid=0), you can find them.

> For example, there are two pairs of characters and only two pairs where a character with spacing value W has EAW=N. (They are tone marks). I would like to understand whether Unicode's EAW classification for them is incorrect or whether they should have been classified as A.

This one I missed in the first place, and raised at #21, with the data diff. Let's discuss there.

> Also, there is no case of W assigned to a character with EAW=A. Which means that the algorithm treats all EAW=A characters as resolved to "Narrow" (or they aren't letters). I would like to understand better whether that assumption holds without exception.

I think it's primarily because W for auto-spacing is CJK "letters", not CJK "characters". As you know, EAW=A is about unified code points between legacy CJK and non-CJK encodings, and CJK "letters" can hardly exist in non-CJK legacy encodings. They are symbols, punctuations, and non-CJK letters (such as used as currency signs, unit characters, etc.) and thus they should be `O` or `N`. Between `O` and `N` is hard though.

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/765 for further comments.

**Comment by kojiishi** [comment]
Closed at https://github.com/unicode-org/unicodetools/issues/765.
