### ISSUE TITLE
Unicode VS and advocating fonts/layout engines

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#17]
This issue is to track @macnmm's [comment on the CSS github](https://github.com/w3c/csswg-drafts/issues/9479#issuecomment-2011023853).

**Comment by kojiishi** [comment]
I fully agree with @macnmm that the Unicode spec alone isn't sufficient to implement the inter-script spacing. The Unicode spec is intended as not a replacement, but is a supplement to the CSS [`text-autospace`] property. From that point of view, IIUC, we're in consensus.

fantasai raised a concern at the CSS github that maintaining the [Text Spacing Character Classes](https://drafts.csswg.org/css-text-4/#text-spacing-classes) for new code points is one of the concern for the CSS WG. This is more concern for [`text-autospace`] than [`text-spacing-trim`], as the latter is more specific and limited. That's where the Unicode spec can help.

For the actual amount of the spacing, including the minimum, desired, and maximum as you suggested, should be in the CSS spec. Currently, the [`text-autospace`] defines it to be 1/8 em, and the Unicode spec proposal defines it as:
> The exact amount of the spacing can vary across documents. This property doesn’t define the exact amount. Instead, it should be defined by high-level protocols or applications such as through markup or by the preferences of a layout application.

This is a collaboration similar to [UAX#50], where Unicode delegates high-level protocols to define more exact behaviors.

@macnmm's comment also includes a proposal to add variation selectors to distinguish unified code points. @kenlunde is the best expert in this area, but from what I know, this is a long discussed topic at UTC, and is still being discussed. The first proposal IIUC is [L2/18-013] by @kenlunde, replaced by [L2/18-073]. Last year, @kenlunde tried a revised, more focused proposal [L2/23-212R], and this was accepted as you might know.

I think it's worth a separate proposal, that can impact not only inter-script spacing, but also [UAX#11] EAST ASIAN WIDTH, [UAX#50] UNICODE VERTICAL TEXT LAYOUT, and may be more. When it was accepted, we'll need to update all relevant specs including the inter-script spacing.

[L2/18-013]: https://www.unicode.org/L2/L2018/18013-svs-proposal.pdf
[L2/18-073]: https://www.unicode.org/L2/L2018/18073-svs-proposal.pdf
[L2/23-212R]: https://www.unicode.org/L2/L2023/23212r-quotes-svs-proposal.pdf
[`text-autospace`]: https://drafts.csswg.org/css-text-4/#text-autospace-property
[`text-spacing-trim`]: https://drafts.csswg.org/css-text-4/#text-spacing-trim-property
[UAX#11]: https://unicode.org/reports/tr11/
[UAX#50]: https://unicode.org/reports/tr50/

**Comment by asmusf** [comment]
There's a general approach to help fine tune the presentation of unified characters using variation selectors. Spacing behavior may only be one part of this, but if we define character classes that trigger East Asian Spacing  behavior then we would need to track how variation sequences affect these classifications.

I think we need an specific issue for this topic and copy / reference all relevant notes to / from there.

**Comment by kojiishi** [comment]
In case anyone not subscribing to CSS, @kidayasuo [replied](https://github.com/w3c/csswg-drafts/issues/9479#issuecomment-2024250811) to @macnmm. IIUC this is inline with my comment above.

**Comment by kojiishi** [comment]
Thank you @asmusf, I think your comment let me find my error. @macnmm's first bullet item:
> Solve the Unicode SJIS unification issue with [Variation Selectors](https://www.unicode.org/L2/L2023/23212r-quotes-svs-proposal.pdf)

can indicate two different things:
1. The auto-spacing should recognize the already accepted VS sequences such as [L2/23-212R](https://www.unicode.org/L2/L2023/23212r-quotes-svs-proposal.pdf).
2. Adopt the VS to all other EA=A characters to solve the Unicode SJIS unification.

I'm sorry that I originally thought it's only about the point 2, so let me correct myself.

My comment above is only about the point 2, but @macnmm is right about the point 1. I'll think about updating the proposal to include it, and review other VS too.

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/766 for further comments.

**Comment by macnmm** [comment]
As I replied in the CSS thread, I am saying that Japanese layout behavior logic currently depends on knowledge of the actual glyphs designs in fonts and their layout intent, and that there are no standards mapping a given codepoint to a glyph that has:

1. a standard width (e.g. full width monospaced, half-width monospaced, half-width proportional, etc)
2. a standard spacing behavior as defined in the JIS X 4051 standard, including minimum, desired, maximum, compression priority, expansion priority.
3. a standard vertical writing posture, which could be derived from #1 if we agree a posture can be inferred from a width class, but having it separate is most flexible

Fonts, having glyphs for several writing scripts at once, are all over the place in how they design default glyphs for a given codepoint and how they add alternates. This makes it very difficult for layout engines not to rely on unique and fragile layout heuristics.

**Comment by kojiishi** [comment]
Closing as https://github.com/unicode-org/unicodetools/issues/766 was closed.
