### ISSUE TITLE
Rename the name to "East Asian Spacing"?

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#18]
Proposed by @asmusf. I have no objections, given the spec is a lot more about East Asian typography.

Please comment if anyone has objections.

**Comment by kojiishi** [comment]
@xfq @kidayasuo

**Comment by kidayasuo** [comment]
I agree if your current intention is to limit it to CJK. You once talked about a possibility of covering non-CJK languages such as French?

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/767 for further comments.

**Comment by kojiishi** [comment]
Wrong issue number.

**Comment by kojiishi** [comment]
https://github.com/unicode-org/unicodetools/issues/767 was closed.
