### ISSUE TITLE
Should `EA=N|Na` excluded from the `W` set?

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#21]
When excluding `EA=W` from the `N` set turned out to be necessary in #15 and implemented in #19, logically speaking, I thought that `EA=Na` and `EA=N` should be excluded from the `W` set, because `H`, `N`, and `Na` are "narrow" in [UAX#11].

I tried this and found that it changes 10 code points from `W` to `O`.
* [Diff of the data file](https://github.com/kojiishi/unicode-auto-spacing/pull/20/files)
* [Changed code points at Unicode Tools](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5Cu02EA-%5Cu02EB%5CuA700-%5CuA707%5D&g=&i=gc%2Csc%2Cscx%2Cea)

The diff is minor, all about `GC=Sk`, so it should have little impact, but it looks to me that their auto-spacing value should stay `W`.

@xfq Thoughts?
@asmusf @kenlunde Do you happen to know why they are `EA=N`?

[UAX#11]: https://unicode.org/reports/tr11/

**Comment by asmusf** [comment]
We need to establish as principle that it is OK to question the EAW assignments. One of the reasons for suggesting that we take EAW into account is that this serves as a useful check for potentially mistaken EAW assignments.

Generally, if some characters are assumed to be used typically with alphabetic (proportional) strings they may be given EAW=N. However, if that assumption is wrong, that would mean the property value is incorrect. If there's no use in a proportional context, they should have been assigned EAW=W instead. Sometimes there's concurrent use in a "wide" context. Such characters should have been given EAW=A instead. 

I don't have direct information on these particular characters, but if there is the idea that they behave like W in EA Spacing, then they might qualify as either A or W.

**Comment by xfq** [comment]
I just added a comment in #20.

**Comment by asmusf** [comment]
I have replied to the comment in #20

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/768 for further comments.

**Comment by kojiishi** [comment]
Fixed by https://github.com/kojiishi/unicode-auto-spacing/pull/20
