### ISSUE TITLE
Consider making U+3013 GETA MARK "W"

### ISSUE THREAD

**Issue by kidayasuo** [kojiishi/unicode-auto-spacing#22]
This character works as a place holder when a Kanji is not available. A modern example is that newspaper or publisher sites use this character when the Kanji is outside of the set of allowed characters (e.g. JIS) in their house rule.

This is an exception to the general rule of making symbols "O". Therefore, although classifying this as 'W' is desirable, we need to assess the advantages and disadvantages.

examples:
https://publications.asahi.com/product/4870.html
https://publications.asahi.com/product/10669.html

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/769 for further comments.
