### ISSUE TITLE
Are part of CJK Unified Ideographs `O`?

### ISSUE THREAD

**Issue by 747** [kojiishi/unicode-auto-spacing#23]
I found a very small portion of CJK Ideographs marked `O` unlike the rest being `W`. Is there any specific reason for this?
https://github.com/kojiishi/unicode-auto-spacing/blob/58c5c98bbd716a69d2f4ba8927f8a9ce8b6abcd0/auto-spacing.txt#L625
https://github.com/kojiishi/unicode-auto-spacing/blob/58c5c98bbd716a69d2f4ba8927f8a9ce8b6abcd0/auto-spacing.txt#L1054
https://github.com/kojiishi/unicode-auto-spacing/blob/58c5c98bbd716a69d2f4ba8927f8a9ce8b6abcd0/auto-spacing.txt#L1056

**Comment by kojiishi** [comment]
Please use https://github.com/unicode-org/unicodetools/issues/770 for further comments.

**Comment by kojiishi** [comment]
Fixed by https://github.com/kojiishi/unicode-auto-spacing/pull/25.
