### ISSUE TITLE
Make EAW=H to O?

### ISSUE THREAD

**Issue by kojiishi** [kojiishi/unicode-auto-spacing#3]
@kidayasuo @xfq

I think I raised this somewhere in CSSWG, but want to confirm, are we good to make [EAW=H](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3Aea%3DH%3A%5D&g=&i=sc%2Cscx%2CIdeo%2CUIdeo) to O?

**Comment by kojiishi** [comment]
Please see the diff at
https://github.com/kojiishi/unicode-auto-spacing/pull/4

**Comment by xfq** [comment]
+0 (no strong opinion) on this.
